apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /jx-boot-job
  name: jx-boot-job
subjects:
- kind: ServiceAccount
  name: jx-boot-job
  namespace: jx-git-operator
roleRef:
  kind: ClusterRole
  name: jx-boot-job
  apiGroup: rbac.authorization.k8s.io
